[profile.default]
src = 'contracts'
out = 'artifacts/foundry'
libs = ["node_modules", "lib"]
test = 'test/foundry'
cache_path = 'cache/foundry'
solc_version = '0.8.23'  # Using a version compatible with OpenZeppelin 5.0.1 which requires ^0.8.20
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]

# For CI
[profile.ci]
verbosity = 4

# For more detailed gas reporting
[profile.gas]
gas_reports = ["*"]
